from __future__ import annotations

DEFAULT_ENVIRONMENT = "development"
DEFAULT_DEBUG = True
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_API_HOST = "127.0.0.1"
DEFAULT_API_PORT = 8000
DEFAULT_CORS_ORIGINS = ["http://127.0.0.1:5173", "http://localhost:5173"]

DEFAULT_DATABASE_PATH = "database/missions.sqlite"

DEFAULT_MAVSDK_ADDRESS = "udp://:14540"
DEFAULT_DRONE_CONNECTION_TIMEOUT_SECONDS = 10.0
DEFAULT_TELEMETRY_REFRESH_INTERVAL_SECONDS = 2.0
DEFAULT_TELEMETRY_READ_TIMEOUT_SECONDS = 1.0
DEFAULT_MISSION_UPLOAD_TIMEOUT_SECONDS = 30.0
DEFAULT_MISSION_TIMEOUT_SECONDS = 60.0

DEFAULT_VALIDATION_MINIMUM_WAYPOINTS = 2
DEFAULT_VALIDATION_MAXIMUM_WAYPOINTS = 100
DEFAULT_VALIDATION_MINIMUM_ALTITUDE_METERS = 5.0
DEFAULT_VALIDATION_MAXIMUM_ALTITUDE_METERS = 120.0
DEFAULT_VALIDATION_MINIMUM_SPEED_METERS_PER_SECOND = 1.0
DEFAULT_VALIDATION_MAXIMUM_SPEED_METERS_PER_SECOND = 15.0
DEFAULT_VALIDATION_HIGH_SPEED_WARNING_METERS_PER_SECOND = 12.0
DEFAULT_VALIDATION_DISTANCE_WARNING_METERS = 5000.0
DEFAULT_VALIDATION_CLOSE_WAYPOINT_WARNING_METERS = 2.0

