from __future__ import annotations

DEFAULT_ENVIRONMENT = "development"
DEFAULT_DEBUG = True
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_LOG_DIRECTORY = "logs"
DEFAULT_LOG_MAX_FILE_SIZE_BYTES = 5_242_880
DEFAULT_LOG_RETENTION_DAYS = 14
DEFAULT_LOG_CONSOLE_ENABLED = True
DEFAULT_LOG_FILE_ENABLED = True
DEFAULT_API_HOST = "127.0.0.1"
DEFAULT_API_PORT = 8000
DEFAULT_CORS_ORIGINS = ["http://127.0.0.1:5173", "http://localhost:5173"]

DEFAULT_DATABASE_PATH = "database/missions.sqlite"

DEFAULT_MAVSDK_ADDRESS = "udp://:14540"
DEFAULT_DRONE_CONNECTION_TIMEOUT_SECONDS = 10.0
DEFAULT_TELEMETRY_REFRESH_INTERVAL_SECONDS = 2.0
DEFAULT_TELEMETRY_READ_TIMEOUT_SECONDS = 1.0
DEFAULT_MISSION_UPLOAD_TIMEOUT_SECONDS = 30.0
DEFAULT_MISSION_TIMEOUT_SECONDS = 60.0

DEFAULT_VALIDATION_MINIMUM_WAYPOINTS = 2
DEFAULT_VALIDATION_MAXIMUM_WAYPOINTS = 100
DEFAULT_VALIDATION_MINIMUM_ALTITUDE_METERS = 5.0
DEFAULT_VALIDATION_MAXIMUM_ALTITUDE_METERS = 120.0
DEFAULT_VALIDATION_MINIMUM_SPEED_METERS_PER_SECOND = 1.0
DEFAULT_VALIDATION_MAXIMUM_SPEED_METERS_PER_SECOND = 15.0
DEFAULT_VALIDATION_HIGH_SPEED_WARNING_METERS_PER_SECOND = 12.0
DEFAULT_VALIDATION_DISTANCE_WARNING_METERS = 5000.0
DEFAULT_VALIDATION_CLOSE_WAYPOINT_WARNING_METERS = 2.0

DEFAULT_PREFLIGHT_BATTERY_WARNING_THRESHOLD_PERCENT = 30.0
DEFAULT_PREFLIGHT_GPS_MINIMUM_SATELLITES = 6
DEFAULT_PREFLIGHT_OPTIONAL_CHECKS_ENABLED = True

DEFAULT_ANALYTICS_MAXIMUM_RECOMMENDED_DISTANCE_METERS = 5000.0
DEFAULT_ANALYTICS_BATTERY_WARNING_THRESHOLD_PERCENT = 25.0
DEFAULT_ANALYTICS_AVERAGE_SPEED_WARNING_METERS_PER_SECOND = 12.0
DEFAULT_ANALYTICS_MAXIMUM_RECOMMENDED_CLIMB_METERS = 100.0
DEFAULT_ANALYTICS_SHARP_TURN_WARNING_COUNT = 5

DEFAULT_VALIDATION_ENGINE_MINIMUM_WAYPOINTS = 2
DEFAULT_VALIDATION_ENGINE_MAXIMUM_WAYPOINTS = 100
DEFAULT_VALIDATION_ENGINE_MINIMUM_ALTITUDE_METERS = 5.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_ALTITUDE_METERS = 120.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_ALTITUDE_JUMP_METERS = 60.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_CLIMB_RATE_METERS_PER_SECOND = 3.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_DESCENT_RATE_METERS_PER_SECOND = 3.0
DEFAULT_VALIDATION_ENGINE_MINIMUM_SPEED_METERS_PER_SECOND = 1.0
DEFAULT_VALIDATION_ENGINE_CRUISE_SPEED_METERS_PER_SECOND = 12.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_SPEED_METERS_PER_SECOND = 15.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_MISSION_DISTANCE_METERS = 5000.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_SINGLE_LEG_DISTANCE_METERS = 2000.0
DEFAULT_VALIDATION_ENGINE_MINIMUM_WAYPOINT_SPACING_METERS = 2.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_FLIGHT_TIME_SECONDS = 900.0
DEFAULT_VALIDATION_ENGINE_MAXIMUM_BATTERY_USAGE_PERCENT = 75.0
DEFAULT_VALIDATION_ENGINE_MINIMUM_BATTERY_RESERVE_PERCENT = 25.0
DEFAULT_VALIDATION_ENGINE_SHARP_TURN_WARNING_DEGREES = 110.0
DEFAULT_VALIDATION_ENGINE_SHARP_TURN_ERROR_DEGREES = 145.0
