from __future__ import annotations

EARTH_RADIUS_METERS = 6_371_000
BATTERY_BASE_USAGE_PERCENT = 3.0
BATTERY_USAGE_PER_KILOMETER_PERCENT = 4.0
BATTERY_USAGE_PER_CLIMB_METER_PERCENT = 0.02
BATTERY_USAGE_PER_WAYPOINT_PERCENT = 0.25
SHARP_TURN_DEGREES = 100.0
